### ISSUE TITLE
Close/collapse  all other cards when any one card under "sessions" list is clicked.

### ISSUE THREAD

**Issue by abhaychaware** [abhaychaware/chhotescientists#13]
Close/collapse  all other cards when any one card under "sessions" list is clicked.  At any point of time, only one card should be open, This will avoid overlapping/partially covering cards during the collapse animation. 

This will also improve user experience as user will know exactly which session he/she clicked to submit the questionnaire

**Comment by grahamearley** [comment]
Done, see PR #15
