### ISSUE TITLE
Beautify the events panel under sessions

### ISSUE THREAD

**Issue by abhaychaware** [abhaychaware/chhotescientists#5]
Beautify events panel under sessions, use blue coloured buttons, may be wounded corners, white font, and so on.

**Comment by grahamearley** [comment]
Updated buttons to be rounded and blue with ripple and white text. Also formatted date according to user's locale. See #9.

Before: 
![image](https://cloud.githubusercontent.com/assets/7142273/17910196/740866f6-694d-11e6-918e-1f5e6b43512a.png)

After:
![image](https://cloud.githubusercontent.com/assets/7142273/17910198/7939d5b0-694d-11e6-9694-2ab6daee66bb.png)

**Comment by grahamearley** [comment]
Is there anything else you were looking for in the visuals here?

**Comment by abhaychaware** [comment]
Hi Grahem, This is exactly what I had in mind.  Can we implement similar changes in the questionnaire screen ?
